#!/bin/bash

DIR="/home/lucadario/Tesi/Tesi-Laurea-Triennale-Informatica-Padova/
"	
# modificare per scegliere il nome della cartella di destinazione
NAME="tesi"		
# modificiare per scegliere il nome del file di origine (.tex)

if [ ! -d $DIR ];
  then
    mkdir $DIR;
fi

echo --------------------
echo - Inizializzazione -
echo --------------------

pdflatex -output-directory=$DIR $NAME
biber $DIR/$NAME
makeindex -s ./$NAME.ist -t ./$NAME.glg -o ./$NAME.gls ./$NAME.glo
makeindex -s ./$NAME.ist -t ./$NAME.alg -o ./$NAME.acr ./$NAME.acn

# Due volte because Latex

pdflatex -output-directory=$DIR $NAME
biber $DIR/$NAME
makeindex -s ./$NAME.ist -t ./$NAME.glg -o ./$NAME.gls ./$NAME.glo
makeindex -s ./$NAME.ist -t ./$NAME.alg -o ./$NAME.acr ./$NAME.acn

echo -------------------------
echo - Generazione Documento -
echo -------------------------

pdflatex -output-directory=$DIR $NAME
pdflatex -output-directory=$DIR $NAME

echo ---------------------------------
echo - Pulisco e poi apro il file... -
echo ---------------------------------

rm *.acn *.aux *.bbl *.bcf *.glo
rm *.ist *.lof *.lot *.run.xml *.toc
# Per mantenere i log commentare la linea seguente
rm $DIR/*.blg  $DIR/*.log

open $DIR/$NAME.pdf

echo ---------------------------- END -----------------------------
